#!/bin/bash
yellow=$(tput bold)$(tput setaf 3)
txtrst=$(tput sgr0)
echo
echo $yellow'CHAOSHEX Ego program initiated'
#select command in "cast" "scry" "evoke" "invoke" "mantra" "sigil" "cancel"; do
select command in "cast" "mantra" "cancel"; do
        case $command in
                cast ) echo Casting yellow magic spell;
                        echo X will gain glamour of Y;
                        read -p "Enter X: " egox;
                        read -p "Enter Y: " egoy;
                        read -p "$egox will gain glamour of $egoy. Confirm (Y/N) " -i "Y" confirm;
                        case $confirm in
                                [Yy]* ) echo Hacking into reality...; 
                                        sleep 1;
                                        echo Data located.;
                                        sleep 1;
                                        echo Updating reality data.;
					/usr/local/lib/chaoshex/gnosis;
                                        echo;
                                        echo Update complete.
                                        echo Committing changes;
                                        sleep 2;
                                        echo Reality permanently changed.;;
                        esac; 
                        break;;
                scry ) echo scrying; break;;
                evoke ) echo evocation; break;;
                invoke ) echo invocation; break;;
                mantra ) /usr/local/lib/chaoshex/mantra; break;;
                sigil ) echo sigil; break;;
                cancel ) break;;
        esac    
done 
echo $txtrst
echo
