#!/bin/bash
echo
echo To use CHAOSHEX run one of the following commands...
echo 
echo magick
echo love
echo war
echo death
echo sex
echo play
echo work
echo ego
echo psyche
echo about
echo "exit"
echo 
echo Then follow the on screen prompts.
echo 
