#!/bin/bash
purple=$(tput setaf 5)
white=$(tput sgr0)
echo
echo $purple'CHAOSHEX Sex program initiated'
#select command in "cast" "scry" "evoke" "invoke" "mantra" "sigil" "cancel"; do
select command in "cast" "mantra" "cancel"; do
        case $command in
                cast ) echo Casting purple magic spell;
                        echo X will be created;
                        read -p "Enter X: " sexx;
                        read -p "$sexx will be created. Confirm (Y/N) " -i "Y" confirm;
                        case $confirm in
                                [Yy]* ) echo Hacking into reality...; 
                                        sleep 1;
                                        echo Data located.;
                                        sleep 1;
                                        echo Updating reality data.;
					/usr/local/lib/chaoshex/gnosis;
                                        echo;
                                        echo Update complete.
                                        echo Committing changes;
                                        sleep 2;
                                        echo Reality permanently changed.;;
                        esac; 
                        break;;
                scry ) echo scrying; break;;
                evoke ) echo evocation; break;;
                invoke ) echo invocation; break;;
                mantra ) /usr/local/lib/chaoshex/mantra; break;;
                sigil ) echo sigil; break;;
                cancel ) break;;
        esac    
done 

echo $white
echo
