#!/bin/bash
red=$(tput setaf 1)
white=$(tput sgr0)
echo
echo $red'CHAOSHEX War program initiated'
#select command in "cast" "scry" "evoke" "invoke" "mantra" "sigil" "cancel"; do
select command in "cast" "mantra" "cancel"; do
	case $command in
		cast ) echo Casting red magic spell;
			echo X will take over Y;
			read -p "Enter X: " warx;
			read -p "Enter Y: " wary;
			#read -p " will take over " confirm;
			read -p "$warx will take over $wary. Confirm (Y/N) " -i "Y" confirm;
			case $confirm in
				[Yy]* ) echo Hacking into reality...; 
					sleep 1;
					echo Data located.;
					sleep 1;
					echo Updating reality data.;
					/usr/local/lib/chaoshex/gnosis;
					echo;
					echo Update complete.
					echo Committing changes;
					sleep 2;			
					echo Reality permanently changed.;;
			esac; 
			break;;
		scry ) echo scrying; break;;
		evoke ) echo evocation; break;;
		invoke ) echo invocation; break;;
		mantra ) /usr/local/lib/chaoshex/mantra; break;;
		sigil ) echo sigil; break;;
		cancel ) break;;
	esac	
done 
echo $white
echo
